// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsHJHj5d_4PbnsgV8v4UroLSfw8Ro91bM',
    appId: '1:183963749176:web:a98a1bd4f289a2519e0fcd',
    messagingSenderId: '183963749176',
    projectId: 'chatting-c8e67',
    authDomain: 'chatting-c8e67.firebaseapp.com',
    storageBucket: 'chatting-c8e67.appspot.com',
    measurementId: 'G-FDNFXFQ0E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWQY8qHYGSvwopl8-rMpcFD-gh5RqJZs',
    appId: '1:183963749176:android:aa6a70635b33bddb9e0fcd',
    messagingSenderId: '183963749176',
    projectId: 'chatting-c8e67',
    storageBucket: 'chatting-c8e67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDtnZ3Cw9KDPFB5FAxKP1PzJ0MBYVuL8',
    appId: '1:183963749176:ios:fb18e8262cb49d3f9e0fcd',
    messagingSenderId: '183963749176',
    projectId: 'chatting-c8e67',
    storageBucket: 'chatting-c8e67.appspot.com',
    iosBundleId: 'com.example.tremorTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaDtnZ3Cw9KDPFB5FAxKP1PzJ0MBYVuL8',
    appId: '1:183963749176:ios:0f0b711d4a2d69759e0fcd',
    messagingSenderId: '183963749176',
    projectId: 'chatting-c8e67',
    storageBucket: 'chatting-c8e67.appspot.com',
    iosBundleId: 'com.example.tremorTrack.RunnerTests',
  );
}
